# Generated by Django 5.2.5 on 2025-09-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("userauths", "0002_user_username_alter_user_client_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Only needed if role = client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.client",
            ),
        ),
    ]
