# Generated by Django 5.2.5 on 2025-09-07 00:15

import userauths.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_user_username_alter_user_client'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userauths.models.CustomUserManager()),
            ],
        ),
    ]
