from django.conf import settings
from django.db import models


class Event(models.Model):
    """
    An event generated by a user. The event can be
    a page view, click, purchase or a custom action.
    """

    EVENT_TYPE_CHOICES = (
        ("page_view", "Page View"),
        ("click", "Click"),
        ("purchase", "Purchase"),
        ("custom", "Custom"),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="events"
    )  # Related to a user from AUTH_USER_MODEL (is the custom User model)
    event_type = models.CharField(max_length=20, choices=EVENT_TYPE_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True)
    metadata = models.JSONField(blank=True, null=True)  # Extra data like device info

    def __str__(self):
        return f"{self.event_type} by {self.user.email} at {self.timestamp}"
